name: audio-switcher # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Switch audio output # 79 char long summary
description: |
  Switch audio output.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  audio-switcher-select:
    plugin: nodejs
    source: https://github.com/twobucks/wethr.git
    stage-package: 
	- pulseaudio
	
apps: 
   audio-switcher-select:
	command: audio-switcher.sh
	plugs:
	   - network 
	   - pulseaudio
	   - desktop      
	   - x11
